[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
go = "1.26.1"
vendir = "latest"
fzf = "latest"
node = "latest"
chezmoi = "latest"
#ollama = "latest"
terraformer = "latest"
rust = "latest"
awscli = "latest"
uv = "latest"
python = "latest"
glab = "latest"
"npm:semantic-release" = "latest"
"npm:@google/gemini-cli" = "latest"
glow = "latest"
fx = "latest"
npm = "latest"
"pipx:copier" = "latest"
task = "latest"
"npm:mcp-searxng" = "latest"
ansible = "latest"
"pipx:marker-pdf" = { version = "latest", full = "" }
ruby = "4.0.1"
hatch = "latest"
ripgrep = "latest"
usage = "latest"
dive = "latest"
pnpm = "latest"
"ubi:docker/cagent" = "latest"
"github:RightNow-AI/openfang" = "latest"
colima = "latest"
helm = "latest"
age = "1.2.1"
delta = "0.18.2"
#"ubi:fleetdm/fleet" = { version = "latest", exe = "fleetctl" }
#"go:github.com/charmbracelet/crush" = "latest"
