[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[tools]
go = "1.24.5"
vendir = "latest"
fzf = "latest"
node = "latest"
chezmoi = "latest"
ollama = "latest"
terraformer = "latest"
mani = "latest"
rust = "latest"
"cargo:awsctx" = "latest"
awscli = "latest"
uv = "latest"
python = "latest"
glab = "latest"
"npm:semantic-release" = "latest"
"pipx:arsenal-cli" = "latest"
"npm:@google/gemini-cli" = "latest"
glow = "latest"
fx = "latest"
